#!/bin/sh

#apt and sudo related
alias apt1='sudo apt-get install'
alias apt2='sudo apt-get remove'
alias apt0='sudo apt-get'
alias purge='sudo apt-get --purge remove'
alias ein='sudo easy_install'
alias rmv='sudo rm -r'

#sytem commands
alias rerc="source /home/tellone/.zshrc"
alias tu="top -o cpu" #processes sorted after cpu usage
alias g="git status"

#shorts for usual commands
alias ce='clear'
alias na='nautilus .'
alias lsd='ls -ld *(-/DN)' # directories only
alias zmv='noglob zmv'
alias ru='noglob ru'
alias lh="ls -d .*/" 
alias cdr="cd ../.."
alias migrate='rake db:migrate && rake db:test:prepare'
alias profileme="history | awk '{print \$2}' | awk 'BEGIN{FS=\"|\"}{print \$1}' | sort | uniq -c | sort -n | tail -n 20 | sort -nr"
#activtion
alias sc_mode="source ~/bin/script_mode"
alias fire='firefox &'
alias playgo='javaws http://files.gokgs.com/javaBin/cgoban.jnlp'
alias trans='transmission-gtk &'
alias phil="mysql -u 'phil' -p"
alias cofig="gvim /home/tellone/gitrepos/current_config/zsh_rcs"
alias ipy="ipython"
#Paths typsets


if [ -d "$HOME/Documents" ]; then
    typeset docs="$HOME/Documents"
    : ~docs
fi
if [ -d "$HOME/keep/ebooks" ]; then
    typeset books="$HOME/keep/ebooks"
    : ~books
fi

