#!/bin/sh

#sytem commands
alias psid="ps -A | ack"
alias rerc="source /home/tellone/.zshrc"
alias tu="top -o cpu" #processes sorted after cpu usage
alias g="git status"
alias aliases="cat $cofig1/aliases"
alias tevim="vim -u /home/tellone/myProjects/tpope/.vimrc"

#shorts for usual commands
alias th='thunar .'
alias ce='clear'
# alias na='nautilus .'
alias lsd='ls -ld *(-/DN)' # directories only
alias lh="ls -d .*/" 
alias profileme="cat $HISTFILE |awk 'BEGIN{FS=\";\"}{print \$2} '| awk '{print\$1}'| sort | uniq -c | sort -n | tail -n 20 | sort -nr"
#Activtion
alias sc_mode="source ~/bin/script_mode"
alias fire='firefox-bin &'
alias playgo='javaws http://files.gokgs.com/javaBin/cgoban.jnlp'
alias trans='transmission-gtk &'
alias phil="mysql -u 'phil' -p"
alias cofig="gvim /home/tellone/current_config/zsh_rcs"
alias ipy="ipython"
alias readvim="gvim -u /home/tellone/.vim/reading-rc.vim"
alias cshaw="cc -Wall -g -DNDEBUG -c -o"
alias migrate='rake db:migrate && rake db:test:prepare'

#{{{java section
alias junit='java -cp .:$(java-config -p junit-4) org.junit.runner.JUnitCore'
alias juc='javac -d -cp .:$(java-config -p junit-4)'

#}}}

#{{{cd related

alias ..='cd ..'
alias ...='cd../..'
alias cd..='cd ..'
alias cd...='cd ../..'
alias cd....='cd ../../..'
alias cd.....='cd ../../../..'
alias cd/='cd /'
alias cdr="cd ../.."
alias rd="rmdir"
alias d='dirs -v | head -10'
#}}}

#{{{ Alterations
alias man='nocorrect man'
alias mv='nocorrect mv'
alias mysql='nocorrect mysql'
alias mkdir='nocorrect mkdir'
alias gist='nocorrect gist'
alias heroku='nocorrect heroku'
alias ebuild='nocorrect ebuild'
alias hpodder='nocorrect hpodder'
alias zmv='noglob zmv'
alias ru='noglob ru'

#}}}

#{{{ Dist-dependent
# if in debian
if [[ -d /usr/apt ]] ; then
    #apt and sudo related
    alias apt1='sudo apt-get install'
    alias apt2='sudo apt-get remove'
    alias apt3='sudo apt-get --dry-run -u dist-upgrade'
    alias apt0='sudo apt-get'
    alias purge='sudo apt-get --purge remove'
    alias ein='sudo easy_install'
fi

#if in gentoo
if [[ -d /usr/portage ]] ; then
    alias emr1='sudo emerge'
    alias emr2='sudo emerge -f'
    alias emr0='sudo emerge -c --pretend'
    alias eix1='sudo eix-sync'
    alias eix0='eix-installed all | grep'
    alias disco='sudo dispatch-conf'
    alias esel='sudo eselect'
fi
#}}}

#Paths typset#{{{


if [ -d "$HOME/Documents" ]; then
    typeset docs="$HOME/Documents"
    : ~docs
fi
if [ -d "$HOME/keep/ebooks" ]; then
    typeset books="$HOME/keep/ebooks"
    : ~books
fi

if [ -d "$HOME/keep/art/justMe" ]; then
    typeset me="$HOME/keep/art/justMe"
    : ~me
fi
#}}}
