#!/bin/zsh

# if in debian
if [[ -d /usr/apt ]] ; then
    #apt and sudo related
    alias apt1='sudo apt-get install'
    alias apt2='sudo apt-get remove'
    alias apt3='sudo apt-get --dry-run -u dist-upgrade'
    alias apt0='sudo apt-get'
    alias purge='sudo apt-get --purge remove'
    alias ein='sudo easy_install'
fi

if [[ -d /usr/portage ]] ; then
    alias emr1='sudo emerge'
    alias emr2='sudo emerge -f'
    alias emr0='sudo emerge -c --pretend'
    alias eix1='sudo eix-sync'
    alias eix0='eix-installed | ack'
    alias disco='sudo dispatch-cofig'
    alias esel='sudo eselect'
fi
