#!/bin/zsh
#
#
#Created: 2012-03-26
#Maintainer: Filip Pettersson
#Email: filip.diloom@gmail.com
#Filename: func_lib
#
#Purpose: To store my functions that i want souced
#	  From the zshrc

#vim section
if [ -f ~/buffer ]; then
    rm ~/buffer
fi
gvim(){ /usr/bin/gvim -f "$@" & true; }


newrails() { 
    wizpath="$HOME/gitrepos/myProjects/ruby_stuff/rails_wiz"
    if [ $# == 1 ]; then
        rails new $1 -m "$wizpath/new_rails1.rb" -T -d mysql
    elif [ $# == 2 ]; then
        rails new $1 -m "$wizpath/new_rails$2.rb" -T
    else
        echo "This function takes one or two inputs"
        exit 1
    fi
    cd $1
    unset wizpath
}
#random
function take {    
    mkdir $1; cd $1
}

namedir() { export $1=$PWD; : ~$1 }

function extract() {
    if [ -f $1 ] ; then
        case $1 in
            *.tar.bz2) tar xvjf $1 ;;
            *.tar.gz) tar xvzf $1 ;;
            *.bz2) bunzip2 $1 ;;
            *.rar) unrar x $1 ;;
            *.gz) gunzip $1 ;;
            *.tar) tar xvf $1 ;;
            *.tbz2) tar xvjf $1 ;;
            *.tgz) tar xvzf $1 ;;
            *.zip) unzip $1 ;;
            *.Z) uncompress $1 ;;
            *.7z) 7z x $1 ;;
            *) echo "'$1' cannot be extracted via >extract<" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

