#!/bin/zsh
#
#
#Created: 2012-03-26
#Maintainer: Filip Pettersson
#Email: filip.diloom@gmail.com
#Filename: func_lib
#
#Purpose: To store my functions that i want souced
#	  From the zshrc

#vim section
if [ -f ~/buffer ]; then
    rm ~/buffer
fi
gvim(){ /usr/bin/gvim -f "$@" & true; }

#Ruby scripts
if [ -x "`which ruby 2>/dev/null`" ]; then
    gems="`ruby -rubygems -e 'puts Gem.dir + %{/gems}' 2>/dev/null`"
    [ -z gems ] || : ~gems
fi

[ ! -f "$HOME/.rvm/scripts/rvm" ] || . "$HOME/.rvm/scripts/rvm"

#random
function take {    
    mkdir $1; cd $1
}

namedir() { export $1=$PWD; : ~$1 }


