#!/bin/zsh
# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="tellone"


if [ -d /home/tellone/current_config/zsh_rcs ]; then
    cofig1=/home/tellone/current_config/zsh_rcs
else
    echo "WARNING!! no zsh_configuration files"
fi

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
which vim &>/dev/null && editor="$(which vim)"

plugins=(extract git python pip rake ruby thor)

source $ZSH/oh-my-zsh.sh
source $cofig1/aliases
source $cofig1/dist_aliases
source $cofig1/zsh_config
source $cofig1/zsh_completion
source $cofig1/func_lib
# Customize to your needs...8
setopt correct_all
