#!/bin/zsh
# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="tellone"


if [ -d /home/tellone/gitrepos/current_config/zsh_rcs ]; then
    cofig1=/home/tellone/gitrepos/current_config/zsh_rcs
else
    echo "WARNING!! no zsh_configuration files"
fi


# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
which vim &>/dev/null && editor="$(which vim)"

export EDITOR="$editor -f"
export VISUAL="$editor
"
export PAGER=/usr/local/bin/vimpager
alias less=$PAGER
alias zless=$PAGER


plugins=(autojump git ruby gems rvm rake python pip terminator thor)


source $ZSH/oh-my-zsh.sh
source $cofig1/aliases
source $cofig1/zsh_config
source $cofig1/zsh_completion
source $cofig1/func_lib
# Customize to your needs...
export PATH=/home/tellone/.rvm/gems/ruby-1.9.2-p290/bin:/home/tellone/.rvm/gems/ruby-1.9.2-p290@global/bin:/home/tellone/.rvm/rubies/ruby-1.9.2-p290/bin:/home/tellone/.rvm/bin:/home/tellone/bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/texlive/2011/bin/i386-linux:/usr/local/MATLAB/R2011a/bin:/usr/local/MATLAB/R2011a/bin/glnx86:/home/tellone/.sm/bin:/home/tellone/.sm/pkg/active/bin:/home/tellone/.sm/pkg/active/sbin

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
