#!/bin/zsh
#
#
#Created: 2012-03-26
#Maintainer: Filip Pettersson
#Email: filip.diloom@gmail.com
#File: env for zsh
#       Deals with Promt, history
#       and gereal option
#


###########################
#setting promt
##########################
setopt prompt_subst

local usercolor="$fg_bold[yellow]"
local dircolor="$fg_bold[blue]"
local vccolor="$fg_bold[black]"
case "$TERM" in
    screen*)
    usercolor=$'\e[38;5;184m'
    dircolor=$'\e[38;5;27m'
    ;;
    xterm*)
        if [ -f $cofig1/tellone.zsh-theme ]; then
            . $cofig1/tellone.zsh-theme
        else
            echo "No file theme found found"
        fi
esac

#############################
# Variables
#############################
which vim &>/dev/null && editor="$(which vim)"

SAVEHIST=1000
HISTSIZE=1000

REPORTTIME=10 # Show elapsed time if command took more than X seconds
LISTMAX=0 # ask to complete if top of list would scroll off screen

# Make CTRL-W delete after other chars, not just spaces
WORDCHARS=${WORDCHARS//[&=\/;\!#%\{]}


# setopt PRINT_EXIT_VALUE

# Other tabbing options
# setopt NO_AUTO_MENU
# setopt BASH_AUTO_LIST


if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

WORDCHARS='*?_-.[]~&;!#$%^(){}<>'
PERIOD=3600
periodic() { rehash }


#domains=(`egrep '^(search|domain)' /etc/resolv.conf 2>/dev/null`)
#[[ -z $domains ]] || shift 1 domains


if [ -x "`which ruby 2>/dev/null`" ]; then
    gems="`ruby -rubygems -e 'puts Gem.dir + %{/gems}' 2>/dev/null`"
    [ -z gems ] || : ~gems
fi

#Setting up path and fpath
export PATH=/home/tellone/bin:/usr/local/sbin:/usr/local/bin:/opt:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/texlive/2011/bin/i386-linux:/home/tellone/myProjects/eclipse_workspace/eclipse
export PAGER=/usr/bin/vimpager
