#!/bin/zsh
#
#
#Created: 2012-03-26
#Maintainer: Filip Pettersson
#Email: filip.diloom@gmail.com
#Filename: config
#
#Purpose: configurations part of the bash shell 
#

if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

autoload -Uz colors && colors
zmodload -i zsh/complist # colorful listingsh
zmodload -i zsh/mathfunc
#zmodload -i zsh/complist
autoload -U zrecompile
autoload -U zmv
autoload -U zsh-mime-setup
autoload -U edit-command-line
autoload url-quote-magic



