#!/bin/zsh
#
#
#Created: 2012-03-26
#Maintainer: Filip Pettersson
#Email: filip.diloom@gmail.com
#File: env for zsh
#       Deals with Promt, history
#       and gereal option
#


###########################
#setting promt
##########################
setopt prompt_subst

local usercolor="$fg_bold[yellow]"
local dircolor="$fg_bold[blue]"
local vccolor="$fg_bold[black]"
case "$TERM" in
    screen*)
    usercolor=$'\e[38;5;184m'
    dircolor=$'\e[38;5;27m'
    ;;
    xterm*|rxvt-unicode)
    usercolor=$'\e[93m'
    dircolor=$'\e[94m'
    ;;
esac
[ $UID = '0' ] && usercolor="$fg_bold[white]"
reset_color=$'\e[00m'

export PS1='%{$vccolor%}$(vcprompt)%{$usercolor%}%n:%{$dircolor%}%~:$%{$reset_color%} '

#############################
# Variables
#############################
HISTFILE=~/.zsh_history
SAVEHIST=1000
HISTSIZE=1000

REPORTTIME=10 # Show elapsed time if command took more than X seconds
LISTMAX=0 # ask to complete if top of list would scroll off screen

# Make CTRL-W delete after other chars, not just spaces
WORDCHARS=${WORDCHARS//[&=\/;\!#%\{]}

#General options

# setopt PRINT_EXIT_VALUE

setopt CORRECT
setopt CORRECTALL

setopt hist_ignore_dups     # ignore duplication command history list
setopt share_history        # share command history data
setopt HIST_IGNORE_SPACE
setopt APPEND_HISTORY # write history only when closing
setopt EXTENDED_HISTORY # add more info

# Other tabbing options
# setopt NO_AUTO_MENU
# setopt BASH_AUTO_LIST

if [[ $ZSH_VERSION == 4.<->* ]]; then
    setopt histexpiredupsfirst histreduceblanks
fi

if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

WORDCHARS='*?_-.[]~&;!#$%^(){}<>'
PERIOD=3600
periodic() { rehash }


#domains=(`egrep '^(search|domain)' /etc/resolv.conf 2>/dev/null`)
#[[ -z $domains ]] || shift 1 domains


if [ -x "`which ruby 2>/dev/null`" ]; then
    gems="`ruby -rubygems -e 'puts Gem.dir + %{/gems}' 2>/dev/null`"
    [ -z gems ] || : ~gems
fi

# [ ! -f "$HOME/.rvm/scripts/rvm" ] || . "$HOME/.rvm/scripts/rvm"

